
data:
    image_size: 384
    channels: 8
    num_workers: 32

model:
    image_size: 384
    num_channels: 32
    num_res_blocks: 3
    learn_sigma: False
    class_cond: False
    use_checkpoint: False
    attention_resolutions: "16,8"
    num_heads: 4
    num_heads_upsample: -1
    use_scale_shift_norm: True
    dropout: 0.0


diffusion:
    var_type: 'fixedsmall'
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1

time_travel:
    T_sampling: 100
    travel_length: 1
    travel_repeat: 1